spring:
  application:
    name: order-orchestrator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  docker:
    compose:
      file: ./order-orchestrator/docker-compose.dev.yaml
      lifecycle-management: start-and-stop   # поднимает при старте, останавливает при завершении
      start:
        command: up                         # использовать `docker compose up`
        arguments: --force-recreate         # ВСЕГДА пересоздавать контейнеры
      stop:
        command: down                     # полностью закрывает контейнеры
        arguments: -v

app:
  async:
    task:
      scheduler:
        batch-size: ${APP_TASK_BATCH_SIZE:100}
        fixed-delay-ms: ${APP_TASK_PROCESSING_DELAY_MS:1000}
        in-progress-timeout-minutes: ${APP_TASK_IN_PROGRESS_TIMEOUT_MINUTES:5}


# настройки Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui

payment:
  stub-url: ${PAYMENT_STUB_URL:http://localhost:8081}
