spring:
  application:
    name: order-orchestrator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  docker:
    compose:
      file: ./order-orchestrator/docker-compose.dev.yaml
      lifecycle-management: start-and-stop   # поднимает при старте, останавливает при завершении
      start:
        command: up                         # использовать `docker compose up`
        arguments: --force-recreate         # ВСЕГДА пересоздавать контейнеры
      stop:
        command: down                     # полностью закрывает контейнеры
        arguments: -v

app:
  async:
    task:
      retry-delay-seconds:  ${APP_TASK_RETRY_DELAY_SECONDS:10}
      retryable-exceptions: ${APP_TASK_RETRYABLE_EXCEPTIONS:feign.RetryableException,java.net.SocketTimeoutException,java.io.IOException}
      non-retryable-exceptions: ${APP_TASK_NON_RETRYABLE_EXCEPTIONS:feign.FeignException$BadRequest,feign.FeignException$Unauthorized,feign.FeignException$Forbidden,feign.FeignException$NotFound,java.lang.IllegalArgumentException,java.lang.IllegalStateException}
      scheduler:
        batch-size: ${APP_TASK_BATCH_SIZE:100}
        fixed-delay-ms: ${APP_TASK_PROCESSING_DELAY_MS:1000}
        in-progress-timeout-minutes: ${APP_TASK_IN_PROGRESS_TIMEOUT_MINUTES:5}
      thread-pool:
        core-pool-size: ${APP_TASK_THREAD_POOL_CORE_POOL_SIZE:10}
        max-pool-size: ${APP_TASK_THREAD_POOL_MAX_POOL_SIZE:50}
        keep-alive-seconds: ${APP_TASK_THREAD_POOL_KEEP_ALIVE_SECONDS:60}
        queue-capacity: ${APP_TASK_THREAD_POOL_QUEUE_CAPACITY:1000}
        await-termination-seconds: ${APP_TASK_THREAD_POOL_AWAIT_TERMINATION_SECONDS:120}
        thread-name-prefix: ${APP_TASK_THREAD_POOL_THREAD_NAME_PREFIX:async-task-pool-}



# настройки Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui

payment:
  stub-url: ${PAYMENT_STUB_URL:http://localhost:8081}
